{% set name = "NCEPLIBS-bufr" %}
{% set version = "12.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-bufr/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a0dad13b905f3e0311e2b50df47418660b47442dfc3843232712044b47f26a71
  patches:  # [py>=312]
    - patches/meson_build.patch  # [py>=312]

build:
  # NOTE: No Windows support in initial feedstock (known use cases are only osx and linux)
  skip: true  # [win]
  skip: true  # [py<310 or py==313]

  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - meson <1.5                             # [py>=312]
    - cmake
    - pkg-config >=0.29
  host:
    - python
    - numpy
  run:
    - python
    - numpy

test:
  commands:
    - test -f ${PREFIX}/lib/libbufr_4${SHLIB_EXT}
  imports:
    - ncepbufr

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-bufr/
  summary: The NCEPLIBS-bufr library contains routines and utilites for working with the WMO BUFR format.
  license: LGPL-3.0-only
  license_file: LICENSE.md
  doc_url: https://noaa-emc.github.io/NCEPLIBS-bufr/

extra:
  recipe-maintainers:
    - darothen
