{% set name = "NCEPLIBS-bufr" %}
{% set version = "12.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-bufr/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6c55923d6b6db251f4e8b16513395a1874ba8c0b3b14d7730e807780f3156ff4

  patches:
        # Rename deprecated functions
    - numpy2.patch

build:
  # NOTE: No Windows support in initial feedstock (known use cases are only osx and linux)
  skip: true  # [win or py<310]

  number: 0

requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - cmake
    - meson
    - pkg-config >=0.29
  host:
    - python
    - numpy
  run:
    - python
    - numpy
    - libgcc >=15.2.0

test:
  commands:
    - test -f ${PREFIX}/lib/libbufr_4${SHLIB_EXT}
  imports:
    - ncepbufr

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-bufr/
  summary: The NCEPLIBS-bufr library contains routines and utilites for working with the WMO BUFR format.
  license: LGPL-3.0-only
  license_file: LICENSE.md
  doc_url: https://noaa-emc.github.io/NCEPLIBS-bufr/

extra:
  recipe-maintainers:
    - darothen
