{% set name = "NCEPLIBS-bufr" %}
{% set version = "12.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-bufr/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 525f26238dba6511a453fc71cecc05f59e4800a603de2abbbbfb8cbb5adf5708

build:
  # NOTE: No Windows support in initial feedstock (known use cases are only osx and linux)
  skip: True  # [win]
  # NOTE: Only support recent Python releases. Cannot support Python==3.12 because build
  # system in NCEPLIBS-bufr_v12.0.1 uses a hard-coded dependency on distutils, which was
  # removed from the standard library.
  skip: True  # [py<310 or py==312]

  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make  # [linux]
    - cmake
    - numpy
    - pkg-config >=0.29
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libbufr_4${SHLIB_EXT}
  imports:
    - ncepbufr

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-bufr/
  summary: The NCEPLIBS-bufr library contains routines and utilites for working with the WMO BUFR format.
  license: LGPL-3.0-only
  license_file: LICENSE.md
  doc_url: https://noaa-emc.github.io/NCEPLIBS-bufr/

extra:
  recipe-maintainers:
    - darothen
